# Generated by Django 4.2.7 on 2023-11-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smiteinfo", "0002_role_alter_champion_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.AddField(
            model_name="champion",
            name="damage_type",
            field=models.CharField(
                choices=[("Magical", "Magical"), ("Physical", "Physical")],
                default="Magical",
                max_length=64,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="champion",
            name="role",
            field=models.CharField(
                choices=[
                    ("Assassin", "Assassin"),
                    ("Guardian", "Guardian"),
                    ("Hunter", "Hunter"),
                    ("Mage", "Mage"),
                    ("Warrior", "Warrior"),
                ],
                default="Mage",
                max_length=64,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
