# Generated by Django 4.2.7 on 2023-11-21 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("smiteinfo", "0004_item_match_matchplayer_alter_champion_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MatchPlayerDetails",
            new_name="MatchPlayerDetail",
        ),
    ]
