# Generated by Django 4.2.7 on 2023-11-21 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("smiteinfo", "0007_alter_champion_damage_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="tier",
        ),
    ]
