# Generated by Django 4.2.7 on 2023-11-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smiteinfo", "0008_remove_item_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchplayer",
            name="won",
            field=models.BooleanField(default=False),
        ),
    ]
