# Generated by Django 4.2.7 on 2023-11-22 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("smiteinfo", "0009_matchplayer_won"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Champion",
            new_name="God",
        ),
    ]
