# Generated by Django 4.2.7 on 2023-11-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smiteinfo", "0010_rename_champion_god"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="god",
            name="id",
        ),
        migrations.AlterField(
            model_name="god",
            name="name",
            field=models.CharField(
                max_length=64, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
