# Generated by Django 4.2.7 on 2023-12-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smiteinfo", "0011_remove_god_id_alter_god_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="god",
            name="win_rate",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
