# Generated by Django 4.2.7 on 2023-12-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smiteinfo", "0012_god_win_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="god",
            name="ban_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="god",
            name="pick_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="banned_gods",
            field=models.ManyToManyField(to="smiteinfo.god"),
        ),
    ]
