# Generated by Django 4.2.7 on 2023-12-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smiteinfo", "0013_god_ban_rate_god_pick_rate_match_banned_gods"),
    ]

    operations = [
        migrations.AddField(
            model_name="god",
            name="prev_ban_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="god",
            name="prev_pick_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="god",
            name="prev_win_rate",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
