# Generated by Django 4.2.7 on 2023-12-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smiteinfo", "0014_god_prev_ban_rate_god_prev_pick_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="banned_gods",
            field=models.ManyToManyField(blank=True, to="smiteinfo.god"),
        ),
    ]
