# Generated by Django 4.2.7 on 2023-12-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smiteinfo", "0016_item_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="god",
            name="top_items",
            field=models.ManyToManyField(blank=True, to="smiteinfo.item"),
        ),
        migrations.AlterField(
            model_name="god",
            name="ban_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="god",
            name="pick_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="god",
            name="prev_ban_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="god",
            name="prev_pick_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="god",
            name="prev_win_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="god",
            name="win_rate",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
