# Generated by Django 4.2.7 on 2024-01-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "smiteinfo",
            "0017_god_top_items_alter_god_ban_rate_alter_god_pick_rate_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="god",
            name="lr_top_items",
            field=models.ManyToManyField(
                blank=True, related_name="lr_top_items_set", to="smiteinfo.item"
            ),
        ),
        migrations.AlterField(
            model_name="god",
            name="top_items",
            field=models.ManyToManyField(
                blank=True, related_name="top_items_set", to="smiteinfo.item"
            ),
        ),
    ]
