# Generated by Django 4.2.7 on 2024-01-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smiteinfo", "0018_god_lr_top_items_alter_god_top_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="damage_type",
            field=models.CharField(
                blank=True,
                choices=[("Magical", "Magical"), ("Physical", "Physical")],
                max_length=64,
            ),
        ),
    ]
