# Generated by Django 4.2.7 on 2024-01-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smiteinfo", "0019_item_damage_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="damage_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Magical", "Magical"),
                    ("Physical", "Physical"),
                    ("Both", "Both"),
                ],
                max_length=64,
            ),
        ),
    ]
